name: LastwarGame
version: 1.0
main: org.lastwar_game.lastwargame.LastWarPlugin
api-version: 1.19
depend: [LastWarGameLogic]
author: YourName
description: Плагин для выбора серверов и подготовки к игре
commands:
  endgame:
    description: Ends the current game
    permission: lastwar.endgame

  stop:
    description: Forcefully resets and stops the game
    permission: lastwar.stop